# Generated by Django 5.0 on 2024-11-30 22:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation_variation_category_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variation_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, help_text='Separado por virgula ,', null=True, size=None, verbose_name='ids_variações'),
        ),
    ]
