# Generated by Django 5.0 on 2024-12-01 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_variation_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='variation_category_list',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='variation_name',
        ),
        migrations.AddField(
            model_name='product',
            name='cobertura',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='complemento',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('complemento', 'complemento'), ('cobertura', 'cobertura')], max_length=100),
        ),
    ]
