# Generated by Django 5.0 on 2024-02-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_method_id",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_type_id",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("New", "Criado"),
                    ("Accepted", "Aceito"),
                    ("await_payment", "Aguardando pagamento"),
                    ("payment_confirmed", "Pagamento Confirmado"),
                    ("waiting_for_shipping", "Aguardando Envio"),
                    ("sent", "Enviado"),
                    ("Completed", "Completd"),
                    ("Cancelled", "Cancelado"),
                ],
                default="New",
                max_length=21,
            ),
        ),
    ]
