# Generated by Django 5.0 on 2024-02-07 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="transaction_data",
            field=models.JSONField(default=dict),
        ),
    ]
