# Generated by Django 5.0 on 2024-02-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_payment_transaction_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="date_of_expiration",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
