# Generated by Django 5.0 on 2024-02-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_payment_date_of_expiration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("New", "Criado"),
                    ("Accepted", "Aceito"),
                    ("await_payment", "Aguardando pagamento"),
                    ("payment_confirmed", "Pagamento Confirmado"),
                    ("payment_error", "Pagamento Confirmado"),
                    ("waiting_for_shipping", "Aguardando Envio"),
                    ("sent", "Enviado"),
                    ("Completed", "Completo"),
                    ("Cancelled", "Cancelado"),
                ],
                default="New",
                max_length=21,
            ),
        ),
    ]
